import fs from "fs";
import http from "http";
import path from "path";
import url from "url";

import {
  Networked3dWebExperienceServer,
  Networked3dWebExperienceServerConfig,
} from "@mml-io/3d-web-experience-server";
import type { CharacterDescription } from "@mml-io/3d-web-user-networking";
import cors from "cors";
import dotenv from "dotenv";
import express from "express";
import enableWs from "express-ws";

import { BasicUserAuthenticator } from "./BasicUserAuthenticator";

const dirname = url.fileURLToPath(new URL(".", import.meta.url));

const PORT = process.env.PORT || 8080;

// Specify the avatar to use here:
const characterDescription: CharacterDescription = {
  // Option 1 (Default) - Use a GLB file directly
  meshFileUrl: "/assets/models/bot.glb", // This is just an address of a GLB file
  // Option 2 - Use an MML Character from a URL
  // mmlCharacterUrl: "https://...",
  // Option 3 - Use an MML Character from a string
  // mmlCharacterString: `
  // <m-character src="/assets/models/mml_body_male.glb">
  //   <m-model src="/assets/models/mml_head_hispanic_male.glb"></m-model>
  //   <m-model src="/assets/models/mml_hair_black.glb"></m-model>
  //   <m-model src="/assets/models/mml_torso_hoodie.glb"></m-model>
  //   <m-model src="/assets/models/mml_legs_grey_pants.glb"></m-model>
  //   <m-model src="/assets/models/mml_shoes_retro_white.glb"></m-model>
  // </m-character>
  // `,
};

const userAuthenticator = new BasicUserAuthenticator(characterDescription, {
  /*
   This option allows sessions that are reconnecting from a previous run of the server to connect even if the present a
   session token that was not generated by this run of the server.

   This is useful for development, but in deployed usage, it is recommended to set this to false.
  */
  devAllowUnrecognizedSessions: true,
});

const webClientBuildDir = path.join(dirname, "../../client/build/");
const indexContent = fs.readFileSync(path.join(webClientBuildDir, "index.html"), "utf8");
const mmlDocumentsDirectoryRoot = path.resolve(dirname, "../mml-documents");
const mmlDocumentsWatchPath = "**/*.html";

dotenv.config();
const { app } = enableWs(express());
app.enable("trust proxy");
app.use(cors());

const networked3dWebExperienceServer = new Networked3dWebExperienceServer({
  networkPath: "/network",
  userAuthenticator,
  mmlServing: {
    documentsWatchPath: mmlDocumentsWatchPath,
    documentsDirectoryRoot: mmlDocumentsDirectoryRoot,
    documentsUrl: "/mml-documents/",
  },
  webClientServing: {
    indexUrl: "/",
    indexContent,
    clientBuildDir: webClientBuildDir,
    clientUrl: "/web-client/",
    clientWatchWebsocketPath:
      process.env.NODE_ENV !== "production" ? "/web-client-build" : undefined,
  },
  enableChat: true,
  assetServing: {
    assetsDir: path.resolve(dirname, "../../../assets/"),
    assetsUrl: "/assets/",
  },
} satisfies Networked3dWebExperienceServerConfig);
networked3dWebExperienceServer.registerExpressRoutes(app);

// Native proxy to forward requests to the compressor server =================
app.use("/asset-compressor/optimize", (req: express.Request, res: express.Response) => {
  const proxyReq = http.request(
    {
      hostname: "localhost",
      port: 8083,
      path: req.originalUrl.replace("/asset-compressor", ""),
      method: req.method,
      headers: req.headers,
    },
    (proxyRes) => {
      res.writeHead(proxyRes.statusCode || 500, proxyRes.headers);
      proxyRes.pipe(res, { end: true });
    },
  );

  req.pipe(proxyReq, { end: true });

  proxyReq.on("error", (err) => {
    console.error("Proxy error:", err);
    res.status(500).send("Proxy error");
  });
});

const assetCompressorBuildDir = path.resolve(dirname, "../../../web-asset-compress/client/build");
// Serve compressor client at /asset-compressor
app.use("/asset-compressor", express.static(assetCompressorBuildDir));
// Handle direct URL access (SPA routing)
app.get("/asset-compressor/*", (_req, res) => {
  res.sendFile(path.join(assetCompressorBuildDir, "index.html"));
});
// ===========================================================================

async function checkLiveStatus(): Promise<boolean> {
  const liveCheckURL = `https://api.cloudflare.com/client/v4/accounts/${process.env.CLOUDFLARE_ACCOUNT_ID}/stream/live_inputs/${process.env.CLOUDFLARE_LIVE_INPUT_ID}`;

  const liveCheckOptions = {
    method: "GET",
    headers: {
      "Content-Type": "application/json",
      "X-Auth-Email": process.env.CLOUDFLARE_AUTH_EMAIL || "",
      Authorization: `Bearer ${process.env.CLOUDFLARE_API_TOKEN}`,
    },
  };

  try {
    const response = await fetch(liveCheckURL, liveCheckOptions);
    const json = await response.json();

    // console.log(`Response from Cloudflare Live Input API: ${JSON.stringify(json)}`);

    const state = json?.result?.status?.current?.state ?? "unknown";
    return state === "connected";
  } catch (err) {
    console.error("error:" + err);
    return false;
  }
}

let lastLiveStatusCheck = 0;
if (
  process.env.CLOUDFLARE_STREAM_URL &&
  process.env.CLOUDFLARE_AUTH_EMAIL &&
  process.env.CLOUDFLARE_API_TOKEN &&
  process.env.CLOUDFLARE_ACCOUNT_ID &&
  process.env.CLOUDFLARE_LIVE_INPUT_ID
) {
  app.get("/live-status", async (req, res) => {
    const now = Date.now();
    if (now - lastLiveStatusCheck < 10000) {
      return res.status(429).json({ message: "Too many requests. Try again later." });
    }
    lastLiveStatusCheck = now;
    const isLive = await checkLiveStatus();
    if (isLive) {
      res.status(200).json({ live: true });
    } else {
      res.status(404).json({ live: false });
    }
  });
}

// Start listening
console.log("Listening on port", PORT);
app.listen(PORT);
